import { s, type SkillDef } from "../types";

export const CLOUD: SkillDef[] = [
  // ── General Cloud Concepts & Architecture ──
  s("cloud-computing", "Cloud Computing", "cloud-concept", ["cloud infrastructure", "cloud services", "iaas paas saas", "cloud engineering"], ["high-demand", "core"]),
  s("multi-cloud", "Multi-Cloud Strategy", "cloud-concept", ["multi cloud", "multi cloud architecture", "cross-cloud deployment"]),
  s("hybrid-cloud", "Hybrid Cloud Architecture", "cloud-concept", ["hybrid cloud", "on-prem to cloud", "direct connect hybrid"]),
  s("cloud-native", "Cloud-Native Architecture (CNCF)", "cloud-concept", ["cloud native development", "cncf landscape", "cloud-native patterns", "12 factor cloud"]),
  s("cloud-migration", "Cloud Migration", "cloud-concept", ["cloud migration strategy", "lift and shift", "replatforming", "refactoring cloud", "application modernization"]),
  s("finops", "Cloud Cost Optimization (FinOps)", "cloud-concept", ["cloud finops", "cloud cost management", "aws cost explorer", "cloud financial management", "reserved instances", "savings plans"], ["high-demand"]),
  s("serverless-architecture", "Serverless Computing", "cloud-concept", ["serverless architecture", "faas", "function as a service", "event-driven serverless", "scale to zero"], ["high-demand", "core"]),
  s("edge-computing", "Edge Computing", "cloud-concept", ["edge functions", "cdn edge", "edge workers", "cloudflare edge", "low latency edge"]),

  // ── Amazon Web Services (AWS) ──
  s("aws", "Amazon Web Services (AWS)", "cloud-platform", ["aws", "aws cloud", "amazon cloud", "amazon web services platform", "aws console"], ["high-demand", "core"]),
  s("aws-ec2", "AWS EC2", "cloud-compute", ["ec2", "elastic compute cloud", "aws ec2 instances", "ec2 auto scaling", "spot instances"]),
  s("aws-s3", "AWS S3", "cloud-storage", ["s3", "simple storage service", "aws s3 bucket", "s3 glacier", "s3 lifecycle rules", "s3 bucket policies"]),
  s("aws-lambda", "AWS Lambda", "cloud-serverless", ["lambda", "aws lambda functions", "serverless lambda", "lambda layers", "lambda provisioned concurrency"]),
  s("aws-ecs", "AWS ECS", "cloud-container", ["ecs", "elastic container service", "aws ecs fargate", "ecs task definitions"]),
  s("aws-eks", "AWS EKS", "cloud-container", ["eks", "elastic kubernetes service", "aws managed kubernetes", "eks blueprints"]),
  s("aws-fargate", "AWS Fargate", "cloud-container", ["fargate", "fargate serverless containers", "aws fargate ecs eks"]),
  s("aws-rds", "AWS RDS", "cloud-database", ["rds", "relational database service aws", "rds postgresql", "rds mysql", "multi-az rds"]),
  s("aws-aurora", "AWS Aurora", "cloud-database", ["aurora", "amazon aurora", "aurora postgres", "aurora mysql", "aurora serverless v2"]),
  s("aws-dynamodb", "AWS DynamoDB", "cloud-database", ["dynamodb aws", "amazon dynamodb database", "dynamodb dax"]),
  s("aws-elasticache", "AWS ElastiCache", "cloud-cache", ["elasticache", "aws redis managed", "aws memcached"]),
  s("aws-memorydb", "AWS MemoryDB for Redis", "cloud-database", ["memorydb", "redis compatible in-memory db"]),
  s("aws-sqs", "AWS SQS", "cloud-messaging", ["sqs", "simple queue service", "aws sqs queues"]),
  s("aws-sns", "AWS SNS", "cloud-messaging", ["sns", "simple notification service", "aws sns topics"]),
  s("aws-eventbridge", "AWS EventBridge", "cloud-events", ["eventbridge", "event bridge", "aws event driven bus", "eventbridge pipes"]),
  s("aws-step-functions", "AWS Step Functions", "cloud-orchestration", ["step functions", "aws state machines", "serverless orchestration"]),
  s("aws-api-gateway", "AWS API Gateway", "cloud-api", ["api gateway aws", "rest api gateway", "http api gateway", "websocket api gateway"]),
  s("aws-appsync", "AWS AppSync", "cloud-api", ["appsync", "graphql appsync", "managed graphql aws"]),
  s("aws-cloudfront", "AWS CloudFront", "cloud-cdn", ["cloudfront", "aws cdn", "cloudfront distributions", "lambda@edge", "cloudfront functions"]),
  s("aws-route53", "AWS Route 53", "cloud-dns", ["route 53", "route53", "aws dns", "route53 latency routing"]),
  s("aws-vpc", "AWS VPC", "cloud-networking", ["vpc", "virtual private cloud", "subnets", "nat gateway", "internet gateway", "vpc peering", "transit gateway", "security groups", "nacl"]),
  s("aws-elb", "AWS Elastic Load Balancing (ALB/NLB)", "cloud-networking", ["elb", "alb", "nlb", "application load balancer", "network load balancer"]),
  s("aws-direct-connect", "AWS Direct Connect", "cloud-networking", ["direct connect", "dx aws"]),
  s("aws-iam", "AWS IAM", "cloud-security", ["iam", "identity and access management aws", "iam roles", "iam policies", "iam users", "least privilege aws"]),
  s("aws-cognito", "AWS Cognito", "cloud-auth", ["cognito", "cognito user pools", "cognito identity pools"]),
  s("aws-secrets-manager", "AWS Secrets Manager", "cloud-security", ["secrets manager", "secret rotation aws"]),
  s("aws-kms", "AWS KMS", "cloud-security", ["kms", "key management service aws", "kms customer managed keys"]),
  s("aws-waf", "AWS WAF", "cloud-security", ["waf aws", "web application firewall aws", "waf acl"]),
  s("aws-shield", "AWS Shield", "cloud-security", ["shield ddos aws", "shield advanced"]),
  s("aws-guardduty", "AWS GuardDuty", "cloud-security", ["guardduty", "threat detection aws"]),
  s("aws-security-hub", "AWS Security Hub", "cloud-security", ["security hub", "cspm aws"]),
  s("aws-cloudwatch", "AWS CloudWatch", "cloud-monitoring", ["cloudwatch", "cloudwatch logs", "cloudwatch metrics", "cloudwatch alarms"]),
  s("aws-cloudtrail", "AWS CloudTrail", "cloud-audit", ["cloudtrail", "api auditing aws"]),
  s("aws-xray", "AWS X-Ray", "cloud-tracing", ["xray", "x-ray distributed tracing"]),
  s("aws-cloudformation", "AWS CloudFormation", "cloud-iac", ["cloudformation", "cfn templates", "aws cfn"]),
  s("aws-cdk", "AWS CDK", "cloud-iac", ["cdk", "cloud development kit", "aws cdk typescript", "aws cdk python"]),
  s("aws-sam", "AWS SAM", "cloud-serverless", ["sam", "serverless application model aws"]),
  s("aws-amplify", "AWS Amplify", "cloud-platform", ["amplify", "aws amplify gen2", "amplify studio"]),
  s("aws-kinesis", "AWS Kinesis", "cloud-streaming", ["kinesis", "kinesis data streams", "kinesis firehose", "kinesis analytics"]),
  s("aws-msk", "AWS MSK (Managed Kafka)", "cloud-streaming", ["msk", "amazon managed streaming for apache kafka"]),
  s("aws-glue", "AWS Glue", "cloud-etl", ["glue", "aws glue etl", "glue data catalog", "glue crawlers"]),
  s("aws-athena", "AWS Athena", "cloud-analytics", ["athena", "serverless sql query s3"]),
  s("aws-emr", "AWS EMR", "cloud-analytics", ["emr", "elastic mapreduce", "spark on aws emr"]),
  s("aws-redshift", "Amazon Redshift", "cloud-data-warehouse", ["redshift", "aws redshift cluster", "redshift serverless"]),
  s("aws-sagemaker", "AWS SageMaker", "cloud-ml", ["sagemaker", "aws machine learning platform", "sagemaker endpoints", "sagemaker pipelines"]),
  s("aws-bedrock", "AWS Bedrock", "cloud-ai", ["bedrock", "aws generative ai", "bedrock foundation models", "bedrock agents"], ["trending"]),
  s("aws-codepipeline", "AWS CodePipeline", "cloud-cicd", ["codepipeline", "aws continuous delivery"]),
  s("aws-codebuild", "AWS CodeBuild", "cloud-cicd", ["codebuild", "aws continuous integration"]),
  s("aws-ecr", "AWS ECR", "cloud-container", ["ecr", "elastic container registry aws"]),

  // ── Microsoft Azure ──
  s("azure", "Microsoft Azure", "cloud-platform", ["azure cloud", "ms azure", "microsoft azure cloud", "azure portal"], ["high-demand", "core"]),
  s("azure-vms", "Azure Virtual Machines", "cloud-compute", ["azure vm", "azure virtual machines"]),
  s("azure-functions", "Azure Functions", "cloud-serverless", ["az functions", "azure serverless functions"]),
  s("azure-app-service", "Azure App Service", "cloud-compute", ["app service azure", "azure web apps"]),
  s("azure-aks", "Azure Kubernetes Service (AKS)", "cloud-container", ["aks", "azure aks", "managed kubernetes azure"]),
  s("azure-container-apps", "Azure Container Apps (ACA)", "cloud-container", ["container apps azure", "keda azure"]),
  s("azure-container-instances", "Azure Container Instances (ACI)", "cloud-container", ["aci", "serverless containers azure"]),
  s("azure-sql-database", "Azure SQL Database", "cloud-database", ["azure sql", "managed sql database azure", "azure sql managed instance"]),
  s("azure-blob-storage", "Azure Blob Storage", "cloud-storage", ["azure storage", "azure blob", "blob container azure"]),
  s("azure-data-lake-storage", "Azure Data Lake Storage (ADLS Gen2)", "cloud-storage", ["adls", "adls gen2", "azure data lake"]),
  s("azure-entra-id", "Microsoft Entra ID (Azure AD)", "cloud-identity", ["azure ad", "aad", "entra id", "azure active directory", "entra id b2c"]),
  s("azure-key-vault", "Azure Key Vault", "cloud-security", ["key vault azure", "azure secrets"]),
  s("azure-defender", "Microsoft Defender for Cloud", "cloud-security", ["azure security center", "azure defender"]),
  s("azure-sentinel", "Microsoft Sentinel", "cloud-security", ["azure sentinel", "cloud native siem azure"]),
  s("azure-devops", "Azure DevOps (ADO)", "cloud-cicd", ["ado", "azure devops services", "azure pipelines", "azure repos", "azure boards"]),
  s("azure-monitor", "Azure Monitor & Log Analytics", "cloud-monitoring", ["azure monitor", "application insights", "azure log analytics", "azure metrics"]),
  s("azure-logic-apps", "Azure Logic Apps", "cloud-integration", ["logic apps", "serverless integration azure"]),
  s("azure-data-factory", "Azure Data Factory (ADF)", "cloud-etl", ["adf", "azure data integration", "adf pipelines"]),
  s("azure-synapse", "Azure Synapse Analytics", "cloud-data-warehouse", ["synapse analytics", "azure sql data warehouse"]),
  s("azure-databricks", "Azure Databricks", "cloud-analytics", ["databricks on azure", "azure spark"]),
  s("azure-openai", "Azure OpenAI Service", "cloud-ai", ["azure openai", "enterprise gpt azure", "azure openai service"], ["trending", "high-demand"]),
  s("azure-ai-search", "Azure AI Search (Cognitive Search)", "cloud-ai", ["azure cognitive search", "azure vector search"]),
  s("azure-machine-learning", "Azure Machine Learning Studio", "cloud-ml", ["azure ml", "aml workspaces"]),
  s("azure-apim", "Azure API Management (APIM)", "cloud-api", ["azure api management", "apim"]),
  s("azure-vnet", "Azure Virtual Network (VNet)", "cloud-networking", ["azure vnet", "vnet peering", "network security groups nsg"]),

  // ── Google Cloud Platform (GCP) ──
  s("gcp", "Google Cloud Platform (GCP)", "cloud-platform", ["gcp", "google cloud", "gcloud", "gcp platform", "google cloud console"], ["high-demand", "core"]),
  s("gcp-compute-engine", "Google Compute Engine (GCE)", "cloud-compute", ["gce", "compute engine", "google virtual machines"]),
  s("gcp-cloud-run", "Google Cloud Run", "cloud-container", ["cloud run", "serverless containers gcp", "cloud run jobs"], ["trending", "high-demand"]),
  s("gcp-gke", "Google Kubernetes Engine (GKE)", "cloud-container", ["gke", "google gke", "gke autopilot", "managed kubernetes gcp"]),
  s("gcp-cloud-functions", "Google Cloud Functions", "cloud-serverless", ["cloud functions gcp", "serverless functions google"]),
  s("gcp-app-engine", "Google App Engine (GAE)", "cloud-compute", ["gae", "app engine standard", "app engine flexible"]),
  s("gcp-cloud-sql", "Google Cloud SQL", "cloud-database", ["cloud sql gcp", "cloud sql postgres", "cloud sql mysql"]),
  s("gcp-cloud-storage", "Google Cloud Storage (GCS)", "cloud-storage", ["gcs", "cloud storage gcp", "gcs buckets"]),
  s("gcp-bigquery", "Google BigQuery", "cloud-analytics", ["bigquery", "bigquery sql", "bigquery ml", "serverless data warehouse gcp"], ["high-demand", "core"]),
  s("gcp-dataflow", "Google Cloud Dataflow", "cloud-data-processing", ["dataflow", "apache beam on gcp"]),
  s("gcp-dataproc", "Google Cloud Dataproc", "cloud-analytics", ["dataproc", "managed spark and hadoop gcp"]),
  s("gcp-vertex-ai", "Google Vertex AI", "cloud-ml", ["vertex ai", "google vertex ai", "gemini on vertex", "vertex ai pipelines", "vertex vector search"], ["trending", "high-demand"]),
  s("gcp-iam", "Google Cloud IAM", "cloud-security", ["gcp iam", "service accounts gcp", "workload identity federation"]),
  s("gcp-cloud-build", "Google Cloud Build", "cloud-cicd", ["cloud build gcp", "serverless cicd google"]),
  s("gcp-artifact-registry", "Google Artifact Registry", "cloud-container", ["artifact registry gcp", "gcr"]),
  s("gcp-cloud-logging", "Google Cloud Logging & Monitoring", "cloud-monitoring", ["stackdriver", "cloud logging", "cloud monitoring gcp"]),
  s("gcp-cloud-armor", "Google Cloud Armor", "cloud-security", ["cloud armor", "ddos waf gcp"]),
  s("gcp-firebase", "Firebase Platform", "cloud-platform", ["firebase", "google firebase", "firebase auth", "firebase hosting", "cloud functions for firebase"], ["high-demand"]),

  // ── Cloudflare, Edge & Modern Platforms ──
  s("cloudflare-platform", "Cloudflare Platform & Workers", "edge-platform", ["cloudflare", "cloudflare workers", "cloudflare pages", "cloudflare r2", "cloudflare d1", "cloudflare kv", "cloudflare vectorize"], ["trending", "high-demand"]),
  s("vercel-platform", "Vercel Platform", "cloud-platform", ["vercel", "vercel deployment", "vercel edge functions", "vercel kv", "vercel blob", "vercel analytics"], ["trending", "high-demand"]),
  s("netlify-platform", "Netlify Platform", "cloud-platform", ["netlify", "netlify functions", "netlify edge", "netlify cms"]),
  s("render-platform", "Render Platform", "cloud-platform", ["render cloud", "render.com", "render web services"]),
  s("flyio-platform", "Fly.io Platform", "cloud-platform", ["fly.io", "flyio", "fly machines", "edge global apps"]),
  s("railway-platform", "Railway Platform", "cloud-platform", ["railway.app", "railway platform"]),
  s("heroku-platform", "Heroku Platform", "cloud-platform", ["heroku", "heroku dynos", "heroku postgres", "heroku buildpacks"]),
  s("digitalocean-cloud", "DigitalOcean", "cloud-platform", ["digital ocean", "digitalocean droplets", "digitalocean kubernetes doks", "digitalocean spaces"]),
  s("hetzner-cloud", "Hetzner Cloud", "cloud-platform", ["hetzner", "hetzner cloud servers"]),
  s("linode-cloud", "Linode (Akamai Cloud)", "cloud-platform", ["linode", "akamai cloud computing"]),
  s("oracle-oci", "Oracle Cloud Infrastructure (OCI)", "cloud-platform", ["oci", "oracle cloud infrastructure", "oracle cloud"]),
  s("ibm-cloud-platform", "IBM Cloud", "cloud-platform", ["ibm cloud", "ibm cloud platform", "red hat on ibm"]),
  s("alibaba-cloud-platform", "Alibaba Cloud", "cloud-platform", ["alibaba cloud", "aliyun", "alibaba compute"]),
];
