import { s, type SkillDef } from "../types";

export const FRONTEND: SkillDef[] = [
  // Core Frameworks & Meta-Frameworks
  s("react", "React", "frontend-framework", ["reactjs", "react.js", "react js", "react framework", "react library", "react frontend", "react 18", "react 19"], ["high-demand", "core"]),
  s("vue", "Vue.js", "frontend-framework", ["vue", "vuejs", "vue js", "vue 3", "vue 2", "vue framework", "composition api", "options api"], ["high-demand", "core"]),
  s("angular", "Angular", "frontend-framework", ["angularjs", "angular js", "angular framework", "angular 2+", "angular 17", "angular 18", "angular signals", "angular cli"], ["high-demand", "core"]),
  s("svelte", "Svelte", "frontend-framework", ["sveltejs", "svelte js", "svelte framework", "svelte 4", "svelte 5", "svelte runes"], ["trending"]),
  s("nextjs", "Next.js", "frontend-meta-framework", ["next", "next js", "nextjs framework", "next.js framework", "vercel next", "next 14", "next 15", "app router", "pages router"], ["high-demand", "core"]),
  s("nuxtjs", "Nuxt.js", "frontend-meta-framework", ["nuxt", "nuxt js", "nuxtjs framework", "nuxt 3", "nuxt bridge"]),
  s("remix", "Remix", "frontend-meta-framework", ["remix run", "remix framework", "remix react", "react router v7"]),
  s("astro", "Astro", "frontend-meta-framework", ["astro framework", "astro build", "astro js", "astro islands"], ["trending"]),
  s("gatsby", "Gatsby", "frontend-meta-framework", ["gatsbyjs", "gatsby js", "gatsby framework", "gatsby graphql"]),
  s("solidjs", "SolidJS", "frontend-framework", ["solid js", "solid.js", "solid framework", "solidstart"]),
  s("qwik", "Qwik", "frontend-framework", ["qwik framework", "qwik builder", "qwik city", "resumability"]),
  s("preact", "Preact", "frontend-framework", ["preactjs", "preact js", "preact signals"]),
  s("lit", "Lit", "frontend-framework", ["lit element", "lit html", "lit web components", "lit-html"]),
  s("alpinejs", "Alpine.js", "frontend-framework", ["alpine js", "alpine", "alpinejs framework"]),
  s("htmx", "htmx", "frontend-library", ["htmx library", "htmx web", "hypermedia htmx"], ["trending"]),
  s("ember", "Ember.js", "frontend-framework", ["emberjs", "ember js", "ember framework", "ember octan"]),
  s("backbone", "Backbone.js", "frontend-framework", ["backbonejs", "backbone js", "marionette js"]),
  s("jquery", "jQuery", "frontend-library", ["jquery library", "j query", "jquery ui", "jquery plugins"]),
  s("stenciljs", "Stencil.js", "frontend-framework", ["stencil web components", "ionic stencil"]),
  s("marko", "Marko", "frontend-framework", ["marko js", "markojs"]),
  s("mithril", "Mithril.js", "frontend-framework", ["mithril", "mithriljs"]),
  s("riotjs", "Riot.js", "frontend-framework", ["riot js", "riotjs"]),

  // Styling, CSS Engines & Preprocessors
  s("tailwindcss", "Tailwind CSS", "styling", ["tailwind", "tailwind css framework", "tailwindcss framework", "tailwind v3", "tailwind v4", "tailwind responsive"], ["high-demand", "core"]),
  s("bootstrap", "Bootstrap", "styling", ["bootstrap css", "bootstrap framework", "twitter bootstrap", "bootstrap 5", "bootstrap 4"]),
  s("styled-components", "Styled Components", "styling", ["styled components react", "css-in-js", "styled-components library"]),
  s("emotion-css", "Emotion", "styling", ["@emotion/react", "@emotion/styled", "emotion css-in-js"]),
  s("css-modules", "CSS Modules", "styling", ["css module", "modular css", "css-modules scoped"]),
  s("vanilla-extract", "vanilla-extract", "styling", ["vanilla extract css", "zero runtime css"]),
  s("panda-css", "Panda CSS", "styling", ["pandacss", "panda css styling"]),
  s("stylex", "StyleX", "styling", ["facebook stylex", "meta stylex"]),
  s("postcss", "PostCSS", "styling-tool", ["post css", "postcss plugins", "autoprefixer", "cssnano"]),
  s("bulma", "Bulma", "styling", ["bulma css", "bulma framework"]),
  s("foundation-css", "Foundation", "styling", ["zurb foundation", "foundation css"]),
  s("semantic-ui", "Semantic UI", "styling", ["semantic ui react", "fomantic ui"]),
  s("unocss", "UnoCSS", "styling", ["uno css", "instant on-demand atomic css"]),
  s("windicss", "Windi CSS", "styling", ["windi", "windicss"]),

  // Component Libraries & Design Systems
  s("shadcn-ui", "shadcn/ui", "component-library", ["shadcn", "shadcn ui", "shadcn react components"], ["trending", "high-demand"]),
  s("material-ui", "Material UI", "component-library", ["mui", "material design react", "material ui react", "mui v5", "mui core"]),
  s("ant-design", "Ant Design", "component-library", ["antd", "ant design react", "ant design vue", "antd mobile"]),
  s("chakra-ui", "Chakra UI", "component-library", ["chakra", "chakra ui react", "chakra ui v3"]),
  s("radix-ui", "Radix UI", "component-library", ["radix", "radix primitives", "radix ui primitives", "@radix-ui"]),
  s("headless-ui", "Headless UI", "component-library", ["tailwind headless ui", "headlessui react"]),
  s("mantine", "Mantine", "component-library", ["mantine ui", "mantine react", "mantine hooks"]),
  s("nextui", "NextUI", "component-library", ["next ui", "heroui", "nextui react"]),
  s("fluent-ui", "Fluent UI", "component-library", ["microsoft fluent ui", "fluent design react"]),
  s("primereact", "PrimeReact", "component-library", ["prime react", "primeng", "primevue", "primefaces"]),
  s("carbon-design", "Carbon Design System", "component-library", ["ibm carbon", "carbon react"]),
  s("base-web", "Base Web", "component-library", ["uber base web", "baseweb"]),
  s("ariakit", "Ariakit", "component-library", ["reakit", "ariakit react"]),
  s("react-aria", "React Aria", "component-library", ["adobe react aria", "react aria components", "react spectrum"]),

  // State Management
  s("redux", "Redux", "state-management", ["redux store", "redux toolkit", "rtk", "react redux", "redux thunk", "redux saga", "redux observable"], ["high-demand", "core"]),
  s("zustand", "Zustand", "state-management", ["zustand state", "zustand react", "zustand store"], ["trending", "high-demand"]),
  s("recoil", "Recoil", "state-management", ["recoil state", "facebook recoil", "recoil js"]),
  s("mobx", "MobX", "state-management", ["mobx state", "mobx react", "mobx state tree", "mst"]),
  s("jotai", "Jotai", "state-management", ["jotai state", "jotai react", "atomic state"]),
  s("xstate", "XState", "state-management", ["xstate state machine", "state machines", "xstate v5", "finite state machines"]),
  s("pinia", "Pinia", "state-management", ["pinia vue", "pinia store", "vue pinia"]),
  s("vuex", "Vuex", "state-management", ["vuex store", "vuex 4", "vue state"]),
  s("ngrx", "NgRx", "state-management", ["ngrx store", "ngrx effects", "ngrx angular"]),
  s("ngxs", "NGXS", "state-management", ["ngxs store", "ngxs angular"]),
  s("signals", "Signals (Reactive State)", "state-management", ["solid signals", "preact signals", "angular signals"]),
  s("effector", "Effector", "state-management", ["effector js", "effector state"]),
  s("valtio", "Valtio", "state-management", ["valtio proxy", "valtio react"]),

  // Data Fetching, Caching & Client-Side API Clients
  s("tanstack-query", "TanStack Query", "client-data", ["react query", "tanstack react query", "vue query", "svelte query", "tanstack query v5"], ["high-demand", "core"]),
  s("swr", "SWR", "client-data", ["vercel swr", "stale while revalidate", "swr react"]),
  s("apollo-client", "Apollo Client", "client-data", ["apollo graphql client", "apollo react", "apollo cache", "@apollo/client"]),
  s("relay", "Relay", "client-data", ["relay graphql", "relay react", "facebook relay", "relay compiler"]),
  s("urql", "urql", "client-data", ["urql graphql", "formidable urql"]),
  s("trpc-client", "tRPC Client", "client-data", ["trpc react", "trpc nextjs", "end-to-end typesafe apis"]),
  s("axios", "Axios", "client-data", ["axios http", "axios interceptors", "axios client"]),
  s("fetch-api", "Fetch API", "client-data", ["window fetch", "native fetch", "whatwg fetch"]),

  // Routing & Form Management
  s("react-router", "React Router", "routing", ["react router dom", "react router v6", "react router v7", "remix router"]),
  s("tanstack-router", "TanStack Router", "routing", ["tanstack router", "typesafe router"]),
  s("vue-router", "Vue Router", "routing", ["vue router 4", "vue routing"]),
  s("react-hook-form", "React Hook Form", "forms", ["react hook form library", "rhf", "useForm react"], ["high-demand"]),
  s("formik", "Formik", "forms", ["formik forms", "formik react", "formik validation"]),
  s("final-form", "React Final Form", "forms", ["final form", "react final form"]),
  s("zod-validation", "Zod Schema Validation", "validation", ["zod schema", "zod typescript", "zod parser"], ["trending", "high-demand"]),
  s("yup-validation", "Yup Validation", "validation", ["yup schema", "yup validator"]),
  s("valibot", "Valibot", "validation", ["valibot schema", "modular validation"]),

  // Bundlers, Build Tools, Compilers & Monorepos
  s("webpack", "Webpack", "bundler", ["webpack bundler", "webpack build", "webpack 5", "webpack plugins", "webpack loaders", "module federation"], ["high-demand", "core"]),
  s("vite", "Vite", "bundler", ["vite build", "vite bundler", "vitejs", "vite plugins", "rolldown"], ["trending", "high-demand"]),
  s("parcel", "Parcel", "bundler", ["parcel bundler", "parcel build", "parcel 2"]),
  s("esbuild", "esbuild", "bundler", ["esbuild bundler", "es build", "esbuild optimizer"]),
  s("rollup", "Rollup", "bundler", ["rollupjs", "rollup bundler", "rollup plugins"]),
  s("turbopack", "Turbopack", "bundler", ["turbopack bundler", "vercel turbopack", "turbo bundler"]),
  s("swc", "SWC", "compiler", ["speedy web compiler", "swc rust compiler", "@swc/core"]),
  s("babel", "Babel", "compiler", ["babeljs", "babel compiler", "babel transpiler", "babel presets", "babel plugins"]),
  s("rspack", "Rspack", "bundler", ["rspack bundler", "bytedance rspack", "rust webpack"]),
  s("farm-bundler", "Farm", "bundler", ["farm bundler", "farm fe"]),
  s("nx", "Nx Monorepo", "build-tool", ["nx", "nx workspace", "nrwl nx", "nx monorepo tools"]),
  s("turborepo", "Turborepo", "build-tool", ["turbo repo", "vercel turborepo", "turbo monorepo"]),
  s("lerna", "Lerna", "build-tool", ["lerna monorepo", "lerna js"]),

  // Testing & Quality Tools for Frontend
  s("jest", "Jest", "frontend-testing", ["jest testing", "jest framework", "jest js", "jest snapshots", "ts-jest"], ["high-demand"]),
  s("vitest", "Vitest", "frontend-testing", ["vitest testing", "vitest framework", "vite test"], ["trending", "high-demand"]),
  s("testing-library", "React Testing Library", "frontend-testing", ["rtl", "react testing library", "@testing-library/react", "dom testing library", "user-event"], ["high-demand"]),
  s("storybook", "Storybook", "frontend-tooling", ["storybook ui", "storybook components", "storybook 8", "component documentation"], ["high-demand"]),
  s("cypress-fe", "Cypress Component Testing", "frontend-testing", ["cypress components", "cypress react"]),
  s("playwright-ct", "Playwright Component Testing", "frontend-testing", ["playwright ct", "playwright react"]),
  s("msw", "Mock Service Worker (MSW)", "frontend-testing", ["mock service worker", "msw mock", "msw 2.0"]),

  // Animation, Graphics, Canvas & 3D
  s("framer-motion", "Framer Motion", "animation", ["framer motion react", "motion react", "motion.dev", "framer animations"], ["trending", "high-demand"]),
  s("gsap", "GSAP", "animation", ["greensock", "greensock animation platform", "gsap timeline", "scrolltrigger"]),
  s("threejs", "Three.js", "graphics-3d", ["three js", "threejs 3d", "three.js 3d", "three.js webgl", "r3f", "react three fiber"], ["trending"]),
  s("react-three-fiber", "React Three Fiber", "graphics-3d", ["r3f", "react-three-fiber", "drei"]),
  s("babylonjs", "Babylon.js", "graphics-3d", ["babylon js", "babylon 3d engine"]),
  s("pixijs", "PixiJS", "graphics-2d", ["pixi js", "pixijs 2d engine", "html5 2d rendering"]),
  s("d3js", "D3.js", "data-visualization", ["d3", "d3 js", "data driven documents", "d3 visualization", "d3 charts"]),
  s("chartjs", "Chart.js", "data-visualization", ["chart js", "chartjs charts", "react-chartjs-2"]),
  s("recharts", "Recharts", "data-visualization", ["recharts react", "recharts library"]),
  s("visx", "visx", "data-visualization", ["airbnb visx", "visx react d3"]),
  s("nivo", "Nivo", "data-visualization", ["nivo charts", "nivo react"]),
  s("echarts", "Apache ECharts", "data-visualization", ["echarts", "echarts visualization"]),
  s("mapbox-gl", "Mapbox GL JS", "maps-gis", ["mapbox gl", "mapbox maps", "react mapbox"]),
  s("leaflet", "Leaflet", "maps-gis", ["leafletjs", "leaflet maps", "react leaflet"]),
  s("openlayers", "OpenLayers", "maps-gis", ["openlayers maps", "ol map"]),
  s("webgl", "WebGL", "graphics-api", ["web gl", "webgl graphics", "webgl 2.0", "glsl shaders"]),
  s("webgpu", "WebGPU", "graphics-api", ["web gpu", "next gen web graphics", "wgsl"]),
  s("canvas-api", "Canvas API", "graphics-api", ["html5 canvas", "canvas 2d", "canvas graphics"]),
  s("svg", "SVG", "graphics", ["scalable vector graphics", "svg animation", "svg icons"]),

  // Core Concepts, Web APIs, Architecture & Optimization
  s("pwa", "Progressive Web Apps (PWA)", "web-concept", ["pwa", "progressive web application", "web app manifest", "offline first"]),
  s("service-workers", "Service Workers", "web-api", ["service worker api", "workbox", "cache api"]),
  s("web-workers", "Web Workers", "web-api", ["web worker api", "dedicated worker", "shared worker", "comlink"]),
  s("websockets-client", "WebSockets Client", "web-api", ["websocket client", "browser websocket", "socket.io client"]),
  s("webrtc", "WebRTC", "web-api", ["web rtc", "real-time communication", "peer-to-peer audio video", "datachannel"]),
  s("server-sent-events", "Server-Sent Events (SSE)", "web-api", ["sse", "eventsource", "server sent events"]),
  s("web-components", "Web Components", "web-standard", ["custom elements", "shadow dom", "html templates", "web component standards"]),
  s("micro-frontends", "Micro Frontends", "architecture", ["micro frontend", "microfrontend architecture", "module federation microfrontends", "single-spa"]),
  s("server-components", "React Server Components (RSC)", "web-concept", ["rsc", "server components", "react server actions"]),
  s("ssr", "Server-Side Rendering (SSR)", "web-concept", ["ssr rendering", "server side rendering", "universal javascript", "isomorphic javascript"]),
  s("ssg", "Static Site Generation (SSG)", "web-concept", ["ssg generation", "static generation", "jamstack"]),
  s("isr", "Incremental Static Regeneration (ISR)", "web-concept", ["isr rendering", "nextjs isr"]),
  s("responsive-design", "Responsive Web Design", "web-concept", ["responsive design", "rwd", "mobile responsive", "media queries", "fluid layout", "container queries"], ["core"]),
  s("accessibility", "Web Accessibility (a11y)", "web-standard", ["a11y", "web accessibility", "aria", "wai-aria", "screen reader testing", "keyboard navigation"], ["core"]),
  s("wcag", "WCAG Compliance", "web-standard", ["web content accessibility guidelines", "wcag 2.1", "wcag 2.2", "wcag aa", "wcag aaa"]),
  s("core-web-vitals", "Core Web Vitals (CWV)", "performance", ["cwv", "web vitals", "lcp", "fid", "cls", "inp", "largest contentful paint", "interaction to next paint"], ["trending", "high-demand"]),
  s("frontend-performance", "Frontend Performance Optimization", "performance", ["web performance", "code splitting", "tree shaking", "lazy loading", "bundle analysis", "critical css", "font optimization", "image optimization"]),
  s("cross-browser", "Cross-Browser Compatibility", "web-concept", ["browser compatibility", "cross browser testing", "cross-browser quirks"]),
  s("internationalization", "Internationalization (i18n)", "web-concept", ["i18n", "localization", "l10n", "react-intl", "i18next", "next-intl", "multi-language support"]),
  s("shadow-dom", "Shadow DOM", "web-api", ["encapsulated dom", "shadow root", "scoped styles"]),
  s("web-audio-api", "Web Audio API", "web-api", ["browser audio", "audio synthesis", "audiocontext"]),
  s("indexeddb", "IndexedDB", "web-storage", ["indexed db", "idb", "dexie.js", "browser database"]),
  s("localstorage", "Web Storage API", "web-storage", ["localstorage", "sessionstorage", "client storage"]),
  s("browser-extensions", "Chrome Extension Development", "browser-platform", ["chrome extensions", "browser add-ons", "manifest v3", "content scripts", "extension service worker"]),
];
