import { s, type SkillDef } from "../types";

export const LANGUAGES: SkillDef[] = [
  // Primary Tier 1
  s("python", "Python", "language", ["py", "python3", "python programming", "cpython", "python 3.x", "python 2.x", "py3", "python dev"], ["high-demand", "core"]),
  s("javascript", "JavaScript", "language", ["js", "ecmascript", "es6", "es2015", "es2020", "es2022", "es2023", "vanilla js", "vanilla javascript", "client side javascript", "esnext", "ecma-script"], ["high-demand", "core"]),
  s("typescript", "TypeScript", "language", ["ts", "typescript programming", "typed javascript", "tslang", "type script"], ["high-demand", "core"]),
  s("java", "Java", "language", ["java programming", "java se", "java ee", "core java", "j2ee", "j2se", "jdk", "openjdk", "java 17", "java 21", "java 11", "java 8", "java jvm"], ["high-demand", "core"]),
  s("csharp", "C#", "language", ["c sharp", "c-sharp", "csharp programming", "dotnet c#", "c# .net", "c# 12", "c# 11"], ["high-demand", "core"]),
  s("cpp", "C++", "language", ["c plus plus", "cplusplus", "c++ programming", "cpp programming", "c++ development", "modern c++", "c++11", "c++14", "c++17", "c++20", "c++23", "cpp"], ["high-demand", "core"]),
  s("c", "C", "language", ["c programming", "c language", "ansi c", "gnu c", "c99", "c11", "c23", "embedded c"], ["core"]),
  s("go", "Go", "language", ["golang", "go programming", "go language", "go lang", "google go", "golang dev"], ["high-demand", "core"]),
  s("rust", "Rust", "language", ["rust programming", "rust lang", "rust language", "rustlang", "rust-lang"], ["trending", "high-demand"]),
  s("ruby", "Ruby", "language", ["ruby programming", "ruby language", "ruby lang", "ruby 3.x", "mri ruby"], ["core"]),
  s("php", "PHP", "language", ["php programming", "php development", "php language", "php 8", "php 8.2", "php 8.3", "php 7.x", "modern php"], ["core"]),
  s("swift", "Swift", "language", ["swift programming", "swift language", "apple swift", "swift 5", "swift 6", "swiftlang"], ["mobile", "high-demand"]),
  s("kotlin", "Kotlin", "language", ["kotlin programming", "kotlin language", "kotlin dev", "kotlin jvm", "kotlin multiplatform language"], ["mobile", "high-demand"]),
  s("scala", "Scala", "language", ["scala programming", "scala language", "scala jvm", "scala 3", "scala 2.13", "typelevel scala"], ["data", "backend"]),
  s("r", "R", "language", ["r programming", "r language", "r statistical", "rstats", "r project", "r language programming"], ["data", "analytics"]),
  s("sql", "SQL", "language", ["structured query language", "sql programming", "sql queries", "sql database", "ansi sql", "sql scripting"], ["high-demand", "core"]),

  // Tier 2 Systems, Functional & Scripting
  s("bash", "Bash", "language", ["bash scripting", "shell scripting", "bash shell", "unix shell", "sh scripting", "bourne again shell", "bash 5"], ["devops", "core"]),
  s("powershell", "PowerShell", "language", ["powershell scripting", "windows powershell", "ps1", "powershell core", "pwsh"], ["devops", "cloud"]),
  s("zsh", "Zsh", "language", ["z shell", "zsh scripting", "oh-my-zsh"]),
  s("fish-shell", "Fish Shell", "language", ["fish scripting", "friendly interactive shell"]),
  s("lua", "Lua", "language", ["lua scripting", "lua programming", "lua language", "luajit", "lua 5.4"]),
  s("perl", "Perl", "language", ["perl programming", "perl scripting", "perl language", "perl 5", "perl 6"]),
  s("dart", "Dart", "language", ["dart programming", "dart language", "google dart", "dartlang", "dart 3"]),
  s("elixir", "Elixir", "language", ["elixir programming", "elixir language", "elixir lang", "elixirlang", "beam elixir"]),
  s("erlang", "Erlang", "language", ["erlang programming", "erlang language", "erlang otp", "beam erlang"]),
  s("clojure", "Clojure", "language", ["clojure programming", "clojure jvm", "clojurescript", "clojure lang"]),
  s("haskell", "Haskell", "language", ["haskell programming", "haskell functional", "ghc haskell"]),
  s("ocaml", "OCaml", "language", ["ocaml programming", "ocaml language", "objective caml", "reasonml"]),
  s("fsharp", "F#", "language", ["f sharp", "f-sharp", "fsharp programming", "f# dotnet"]),
  s("groovy", "Groovy", "language", ["groovy programming", "groovy language", "apache groovy"]),
  s("julia", "Julia", "language", ["julia programming", "julia language", "julialang", "scientific julia"]),
  s("zig", "Zig", "language", ["zig programming", "zig language", "ziglang", "zig compiler"]),
  s("nim", "Nim", "language", ["nim programming", "nim language", "nimlang"]),
  s("crystal", "Crystal", "language", ["crystal programming", "crystal language", "crystallang"]),
  s("v-lang", "V", "language", ["vlang", "v programming", "v language"]),
  s("matlab", "MATLAB", "language", ["matlab programming", "mathworks matlab", "matlab scripts"]),
  s("octave", "GNU Octave", "language", ["octave", "gnu octave math"]),
  s("assembly", "Assembly", "language", ["asm", "assembly language", "x86 assembly", "x86-64 assembly", "arm assembly", "risc-v assembly", "nasm", "masm", "gas assembly"]),
  s("objective-c", "Objective-C", "language", ["objc", "objective c", "obj-c", "objective c programming"]),
  s("solidity", "Solidity", "language", ["solidity programming", "solidity smart contracts", "ethereum solidity", "solidity dev"], ["blockchain", "trending"]),
  s("vyper", "Vyper", "language", ["vyper smart contracts", "vyper ethereum", "vyper pythonic"]),
  s("move-lang", "Move", "language", ["move programming", "move language", "aptos move", "sui move", "move smart contracts"]),
  s("cairo", "Cairo", "language", ["cairo lang", "starknet cairo", "cairo zero"]),

  // Legacy & Enterprise Languages
  s("cobol", "COBOL", "language", ["cobol programming", "cobol language", "mainframe cobol", "enterprise cobol"]),
  s("fortran", "Fortran", "language", ["fortran programming", "fortran language", "fortran 90", "fortran 77", "modern fortran"]),
  s("abap", "ABAP", "language", ["sap abap", "abap programming", "abap oo", "advanced business application programming"]),
  s("apex", "Apex", "language", ["salesforce apex", "apex programming", "apex triggers", "apex classes", "apex language"]),
  s("vba", "VBA", "language", ["visual basic for applications", "vba programming", "excel vba", "vb macro", "ms vba"]),
  s("visual-basic", "Visual Basic .NET", "language", ["vb.net", "visual basic net", "vb net"]),
  s("rpg-lang", "RPG", "language", ["rpg iv", "rpg ile", "as400 rpg", "ibm i rpg"]),
  s("actionscript", "ActionScript", "language", ["actionscript 3", "as3", "flash actionscript"]),
  s("ada", "Ada", "language", ["ada programming", "ada 2012", "ada language", "gnat ada"]),
  s("prolog", "Prolog", "language", ["prolog programming", "prolog logic", "swi prolog"]),
  s("lisp", "Lisp", "language", ["lisp programming", "common lisp", "clisp", "elisp", "emacs lisp"]),
  s("racket", "Racket", "language", ["racket programming", "racket scheme"]),
  s("scheme", "Scheme", "language", ["scheme programming", "scheme lisp"]),
  s("smalltalk", "Smalltalk", "language", ["smalltalk programming", "pharo smalltalk", "squeak"]),
  s("pascal", "Pascal", "language", ["pascal programming", "turbo pascal", "free pascal", "delphi", "object pascal"]),
  s("delphi", "Delphi", "language", ["embarcadero delphi", "delphi programming", "delphi pascal"]),
  s("tcl", "Tcl/Tk", "language", ["tcl", "tcl tk", "tool command language"]),
  s("awk", "AWK", "language", ["awk scripting", "gawk", "gnu awk"]),
  s("sed", "Sed", "language", ["sed stream editor", "sed scripting"]),

  // Dialects, Database Query Languages & Extensions
  s("plsql", "PL/SQL", "database-language", ["pl sql", "plsql programming", "oracle plsql", "oracle pl/sql", "procedural sql"]),
  s("tsql", "T-SQL", "database-language", ["t sql", "transact sql", "transact-sql", "sql server tsql", "mssql tsql"]),
  s("plpgsql", "PL/pgSQL", "database-language", ["pl pgsql", "postgres procedural language", "pl/pgsql postgres"]),
  s("cypher", "Cypher", "query-language", ["cypher query language", "neo4j cypher", "open cypher"]),
  s("gremlin", "Gremlin", "query-language", ["apache tinkerpop gremlin", "gremlin graph query"]),
  s("sparql", "SPARQL", "query-language", ["sparql query", "rdf sparql"]),
  s("graphql-lang", "GraphQL Query Language", "query-language", ["graphql schema", "sdl", "graphql queries", "gql"]),
  s("promql", "PromQL", "query-language", ["prometheus query language", "promql metrics"]),
  s("kql", "KQL", "query-language", ["kusto query language", "azure data explorer kql", "log analytics kql"]),
  s("splunk-spl", "Splunk SPL", "query-language", ["search processing language", "splunk search language", "spl"]),
  s("jsoniq", "JSONiq", "query-language", ["json query language"]),
  s("xpath", "XPath", "query-language", ["xpath query", "xml path language"]),
  s("xquery", "XQuery", "query-language", ["xml query language"]),
  s("dax", "DAX", "query-language", ["data analysis expressions", "power bi dax", "tabular dax"]),
  s("power-query-m", "Power Query M", "query-language", ["m language", "power query formula language"]),
  s("hcl", "HCL", "configuration-language", ["hashicorp configuration language", "terraform hcl", "hcl2"]),
  s("dhall", "Dhall", "configuration-language", ["dhall lang", "dhall configuration"]),
  s("jsonnet", "Jsonnet", "configuration-language", ["google jsonnet", "jsonnet templating"]),
  s("cue-lang", "CUE", "configuration-language", ["cuelang", "cue configuration"]),

  // Markup & Formatting Languages
  s("html", "HTML", "markup", ["html5", "hypertext markup language", "html markup", "semantic html", "html5 semantic elements"], ["core"]),
  s("css", "CSS", "styling", ["css3", "cascading style sheets", "css styling", "modern css", "css grid", "css flexbox"], ["core"]),
  s("sass", "SASS/SCSS", "styling", ["sass", "scss", "sass css", "syntactically awesome style sheets", "scss styling"]),
  s("less", "LESS", "styling", ["less css", "less stylesheet", "less preprocessor"]),
  s("stylus", "Stylus", "styling", ["stylus css", "stylus preprocessor"]),
  s("yaml", "YAML", "markup", ["yml", "yaml configuration", "yaml format", "yaml schema"]),
  s("json", "JSON", "format", ["json data", "javascript object notation", "json schema", "json-ld"]),
  s("xml", "XML", "markup", ["xml markup", "extensible markup language", "xsd", "dtd", "xslt"]),
  s("markdown", "Markdown", "markup", ["md", "gfm", "github flavored markdown", "commonmark"]),
  s("mdx", "MDX", "markup", ["markdown jsx", "mdx format", "mdx react"]),
  s("latex", "LaTeX", "markup", ["tex", "latex document", "pdflatex"]),
  s("protobuf", "Protocol Buffers", "format", ["protobuf", "proto", "proto3", "proto2", "google protobuf", "protocol buffer syntax"]),
  s("avro-format", "Apache Avro Format", "format", ["avro schema", "avro data format"]),
  s("parquet-format", "Apache Parquet Format", "format", ["parquet columnar format", "parquet file format"]),
  s("thrift", "Apache Thrift", "format", ["thrift idl", "apache thrift format"]),

  // Hardware Description Languages
  s("verilog", "Verilog", "hardware-language", ["verilog hdl", "system verilog", "verilog programming"]),
  s("systemverilog", "SystemVerilog", "hardware-language", ["system verilog", "sv", "systemverilog verification", "uvm"]),
  s("vhdl", "VHDL", "hardware-language", ["vhdl programming", "vhdl hardware"]),
  s("chisel", "Chisel", "hardware-language", ["chisel hdl", "chisel scala"]),
  s("bluespec", "Bluespec", "hardware-language", ["bsv", "bluespec systemverilog"]),

  // Web & Intermediate Representations
  s("wasm", "WebAssembly", "language", ["wasm", "web assembly", "wat", "webassembly text format", "emscripten wasm"]),
  s("llvm-ir", "LLVM IR", "intermediate-language", ["llvm intermediate representation", "llvm bytecode"]),
  s("spir-v", "SPIR-V", "intermediate-language", ["spirv", "vulkan spir-v"]),
  s("glsl", "GLSL", "shader-language", ["opengl shading language", "glsl shader", "fragment shader", "vertex shader"]),
  s("hlsl", "HLSL", "shader-language", ["high level shading language", "directx hlsl"]),
  s("wgsl", "WGSL", "shader-language", ["webgpu shading language", "wgsl shader"]),
  s("metal-shading", "Metal Shading Language", "shader-language", ["msl", "apple metal shader"]),
  s("cuda-c", "CUDA C/C++", "language", ["cuda programming language", "cuda kernels", "nvidia cuda c"]),
];
