import type { RelDef } from "./types";

export const RELATIONS: RelDef[] = [
  // ── Languages & Foundations ──
  { from: "typescript", to: "javascript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "sass", to: "css", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "less", to: "css", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "stylus", to: "css", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "pyspark", to: "python", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "pyspark", to: "apache-spark", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "elixir", to: "erlang", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "kotlin", to: "java", type: "RELATED_TO", weight: 0.85 },
  { from: "scala", to: "java", type: "RELATED_TO", weight: 0.8 },
  { from: "clojure", to: "java", type: "RELATED_TO", weight: 0.75 },
  { from: "csharp", to: "java", type: "RELATED_TO", weight: 0.8 },
  { from: "cpp", to: "c", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "rust", to: "cpp", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "go", to: "rust", type: "ALTERNATIVE_TO", weight: 0.8 },
  { from: "python", to: "ruby", type: "ALTERNATIVE_TO", weight: 0.85 },

  // ── Frontend Frameworks & Meta-Frameworks ──
  { from: "react", to: "javascript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "vue", to: "javascript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "angular", to: "typescript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "svelte", to: "javascript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "solidjs", to: "javascript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "qwik", to: "typescript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "nextjs", to: "react", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "remix", to: "react", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "gatsby", to: "react", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "nuxtjs", to: "vue", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "astro", to: "javascript", type: "REQUIRES", weight: 1.0, directed: true },

  // Frontend Alternatives
  { from: "react", to: "vue", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "react", to: "angular", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "react", to: "svelte", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "vue", to: "angular", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "vue", to: "svelte", type: "ALTERNATIVE_TO", weight: 0.8 },
  { from: "nextjs", to: "remix", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "nextjs", to: "nuxtjs", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "nextjs", to: "astro", type: "ALTERNATIVE_TO", weight: 0.75 },

  // Styling & UI Libraries
  { from: "tailwindcss", to: "css", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "styled-components", to: "react", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "material-ui", to: "react", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "chakra-ui", to: "react", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "radix-ui", to: "react", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "shadcn-ui", to: "radix-ui", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "shadcn-ui", to: "tailwindcss", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "shadcn-ui", to: "react", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "tailwindcss", to: "bootstrap", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "material-ui", to: "ant-design", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "material-ui", to: "shadcn-ui", type: "ALTERNATIVE_TO", weight: 0.9 },

  // Frontend State & Data Fetching
  { from: "redux", to: "react", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "zustand", to: "react", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "recoil", to: "react", type: "COMPLEMENTARY", weight: 0.8 },
  { from: "mobx", to: "react", type: "COMPLEMENTARY", weight: 0.8 },
  { from: "tanstack-query", to: "react", type: "COMPLEMENTARY", weight: 0.95 },
  { from: "swr", to: "react", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "apollo-client", to: "graphql-api", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "tanstack-query", to: "swr", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "redux", to: "zustand", type: "ALTERNATIVE_TO", weight: 0.9 },

  // Bundlers & Build Tools
  { from: "vite", to: "webpack", type: "ALTERNATIVE_TO", weight: 0.95 },
  { from: "vite", to: "esbuild", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "turbopack", to: "webpack", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "turborepo", to: "nx", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ── Backend Frameworks ──
  { from: "express", to: "nodejs", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "fastify", to: "nodejs", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "nestjs", to: "typescript", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "nestjs", to: "nodejs", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "django", to: "python", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "django-rest-framework", to: "django", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "flask", to: "python", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "fastapi", to: "python", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "spring-boot", to: "java", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "spring-boot", to: "spring-framework", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "quarkus", to: "java", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "aspnet-core", to: "csharp", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "rails", to: "ruby", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "laravel", to: "php", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "symfony", to: "php", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "gin", to: "go", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "fiber", to: "go", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "actix", to: "rust", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "axum", to: "rust", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "phoenix", to: "elixir", type: "REQUIRES", weight: 1.0, directed: true },

  // Backend Alternatives
  { from: "express", to: "fastify", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "express", to: "nestjs", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "django", to: "fastapi", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "django", to: "flask", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "fastapi", to: "flask", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "spring-boot", to: "quarkus", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "gin", to: "fiber", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "actix", to: "axum", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ── Databases, ORMs & Caches ──
  { from: "postgresql", to: "mysql", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "postgresql", to: "sql-server", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "postgresql", to: "oracle-db", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "cockroachdb", to: "postgresql", type: "RELATED_TO", weight: 0.9 },
  { from: "mongodb", to: "couchbase", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "mongodb", to: "dynamodb", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "redis", to: "memcached", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "elasticsearch", to: "opensearch", type: "ALTERNATIVE_TO", weight: 0.98 },
  { from: "elasticsearch", to: "meilisearch", type: "ALTERNATIVE_TO", weight: 0.8 },
  { from: "neo4j", to: "arangodb", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "snowflake", to: "bigquery", type: "ALTERNATIVE_TO", weight: 0.95 },
  { from: "snowflake", to: "amazon-redshift", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ORMs
  { from: "prisma", to: "typescript", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "drizzle-orm", to: "typescript", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "sqlalchemy", to: "python", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "typeorm", to: "typescript", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "hibernate", to: "java", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "entity-framework", to: "csharp", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "mongoose", to: "mongodb", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "prisma", to: "drizzle-orm", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "prisma", to: "typeorm", type: "ALTERNATIVE_TO", weight: 0.85 },

  // ── Cloud & DevOps ──
  { from: "docker", to: "kubernetes", type: "COMPLEMENTARY", weight: 0.95 },
  { from: "kubernetes", to: "helm", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "kubernetes", to: "istio", type: "COMPLEMENTARY", weight: 0.85 },
  { from: "kubernetes", to: "argocd", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "kubernetes", to: "prometheus", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "prometheus", to: "grafana", type: "COMPLEMENTARY", weight: 0.98 },
  { from: "terraform", to: "aws", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "terraform", to: "azure", type: "COMPLEMENTARY", weight: 0.85 },
  { from: "terraform", to: "gcp", type: "COMPLEMENTARY", weight: 0.85 },
  { from: "terraform", to: "opentofu", type: "ALTERNATIVE_TO", weight: 0.98 },
  { from: "terraform", to: "pulumi", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "github-actions", to: "gitlab-ci", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "github-actions", to: "jenkins", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "argocd", to: "fluxcd", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ── Data Engineering ──
  { from: "apache-spark", to: "scala", type: "RELATED_TO", weight: 0.85 },
  { from: "apache-spark", to: "python", type: "RELATED_TO", weight: 0.9 },
  { from: "dbt", to: "sql", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "dbt", to: "snowflake", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "dbt", to: "bigquery", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "apache-airflow", to: "python", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "apache-kafka", to: "rabbitmq", type: "ALTERNATIVE_TO", weight: 0.8 },
  { from: "fivetran", to: "airbyte", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "delta-lake", to: "apache-iceberg", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "tableau", to: "power-bi", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "pandas", to: "polars", type: "ALTERNATIVE_TO", weight: 0.85 },

  // ── AI & Machine Learning ──
  { from: "pytorch", to: "python", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "tensorflow", to: "python", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "scikit-learn", to: "python", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "pytorch", to: "tensorflow", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "pytorch", to: "nvidia-cuda", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "pytorch", to: "numpy", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "langchain", to: "python", type: "REQUIRES", weight: 0.9, directed: true },
  { from: "langchain", to: "langgraph", type: "COMPLEMENTARY", weight: 0.95 },
  { from: "langchain", to: "llamaindex", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "langgraph", to: "crewai", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "rag", to: "embeddings", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "rag", to: "pgvector", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "rag", to: "pinecone", type: "COMPLEMENTARY", weight: 0.9 },
  { from: "pinecone", to: "weaviate", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "pinecone", to: "qdrant", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "pinecone", to: "milvus", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "mlflow", to: "wandb", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "huggingface", to: "pytorch", type: "COMPLEMENTARY", weight: 0.95 },
  { from: "deep-learning", to: "machine-learning", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "generative-ai", to: "deep-learning", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "llm", to: "transformers-architecture", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "prompt-engineering", to: "llm", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "fine-tuning", to: "llm", type: "RELATED_TO", weight: 0.95 },
  { from: "langfuse", to: "langsmith", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ── Mobile ──
  { from: "react-native", to: "react", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "expo-framework", to: "react-native", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "flutter", to: "dart", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "swiftui", to: "swift", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "uikit", to: "swift", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "jetpack-compose", to: "kotlin", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "react-native", to: "flutter", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "swiftui", to: "uikit", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ── Testing ──
  { from: "playwright", to: "cypress", type: "ALTERNATIVE_TO", weight: 0.95 },
  { from: "playwright", to: "selenium-webdriver", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "jest-unit", to: "vitest-unit", type: "ALTERNATIVE_TO", weight: 0.95 },
  { from: "pytest", to: "python", type: "REQUIRES", weight: 0.95, directed: true },
  { from: "k6-load-testing", to: "apache-jmeter", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ── Security ──
  { from: "okta-platform", to: "auth0-platform", type: "RELATED_TO", weight: 0.95 },
  { from: "auth0-platform", to: "keycloak-iam", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "wiz-security", to: "prisma-cloud", type: "ALTERNATIVE_TO", weight: 0.9 },

  // ── Blockchain ──
  { from: "solidity", to: "ethereum", type: "REQUIRES", weight: 1.0, directed: true },
  { from: "foundry-toolkit", to: "hardhat", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "ethers-js", to: "viem-library", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "wagmi-hooks", to: "viem-library", type: "REQUIRES", weight: 0.95, directed: true },

  // ── Design ──
  { from: "figma", to: "sketch-design", type: "ALTERNATIVE_TO", weight: 0.9 },
  { from: "figma", to: "adobe-xd", type: "ALTERNATIVE_TO", weight: 0.85 },
  { from: "figma", to: "framer-tool", type: "RELATED_TO", weight: 0.85 },
];
