import { req, type RoleDef } from "./types";

export const ROLES: RoleDef[] = [
  // ───────────────────────────────────────────────────────────────────
  // 1. Software Engineering & Web Development
  // ───────────────────────────────────────────────────────────────────
  {
    id: "software-engineer",
    title: "Software Engineer",
    aliases: ["software developer", "swe", "sde", "software dev", "programmer", "software development engineer", "application developer", "full stack software engineer", "generalist software engineer", "full stack developer"],
    skills: [
      req("data-structures", 0.95),
      req("algorithms", 0.95),
      req("system-design", 0.85),
      req("git", 0.9),
      req("rest-api", 0.85),
      req("python", 0.75),
      req("javascript", 0.8),
      req("typescript", 0.8),
      req("docker", 0.7),
      req("postgresql", 0.75),
      req("solid-principles", 0.8),
      req("agile-methodology", 0.7),
    ],
  },
  {
    id: "senior-software-engineer",
    title: "Senior Software Engineer",
    aliases: ["senior software developer", "senior swe", "senior sde", "sr software engineer", "sr swe", "sr software developer", "lead software developer"],
    skills: [
      req("system-design", 0.95),
      req("distributed-systems", 0.85),
      req("data-structures", 0.9),
      req("algorithms", 0.9),
      req("microservices-architecture", 0.85),
      req("clean-architecture", 0.85),
      req("code-review", 0.9),
      req("technical-mentoring", 0.85),
      req("docker", 0.8),
      req("postgresql", 0.85),
      req("redis-caching", 0.8),
      req("git", 0.9),
    ],
  },
  {
    id: "frontend-engineer",
    title: "Frontend Engineer",
    aliases: ["frontend developer", "front end developer", "front-end engineer", "frontend dev", "ui developer", "ui engineer", "client side engineer", "web frontend developer", "react frontend engineer"],
    skills: [
      req("javascript", 1.0),
      req("typescript", 0.95),
      req("react", 0.95),
      req("html", 0.95),
      req("css", 0.95),
      req("tailwindcss", 0.85),
      req("nextjs", 0.85),
      req("tanstack-query", 0.8),
      req("responsive-design", 0.9),
      req("accessibility", 0.85),
      req("core-web-vitals", 0.8),
      req("frontend-performance", 0.85),
      req("jest-unit", 0.75),
      req("git", 0.85),
    ],
  },
  {
    id: "senior-frontend-engineer",
    title: "Senior Frontend Engineer",
    aliases: ["senior frontend developer", "sr frontend engineer", "sr front end developer", "lead frontend developer", "staff frontend engineer"],
    skills: [
      req("react", 1.0),
      req("typescript", 1.0),
      req("nextjs", 0.9),
      req("frontend-performance", 0.95),
      req("design-systems-discipline", 0.9),
      req("core-web-vitals", 0.9),
      req("accessibility", 0.9),
      req("micro-frontends", 0.75),
      req("server-components", 0.85),
      req("state-management", 0.85),
      req("vitest-unit", 0.85),
      req("playwright", 0.8),
    ],
  },
  {
    id: "backend-engineer",
    title: "Backend Engineer",
    aliases: ["backend developer", "back end developer", "back-end engineer", "backend dev", "server side developer", "backend software engineer", "api developer", "backend platform engineer"],
    skills: [
      req("nodejs", 0.85),
      req("python", 0.85),
      req("postgresql", 0.9),
      req("rest-api", 0.95),
      req("graphql-api", 0.8),
      req("grpc", 0.75),
      req("redis-caching", 0.85),
      req("apache-kafka", 0.8),
      req("docker", 0.8),
      req("microservices-architecture", 0.85),
      req("system-design", 0.85),
      req("database-indexing", 0.85),
      req("query-optimization", 0.85),
    ],
  },
  {
    id: "senior-backend-engineer",
    title: "Senior Backend Engineer",
    aliases: ["senior backend developer", "sr backend engineer", "sr back end developer", "lead backend developer", "staff backend engineer"],
    skills: [
      req("system-design", 0.95),
      req("distributed-systems", 0.9),
      req("microservices-architecture", 0.9),
      req("postgresql", 0.9),
      req("apache-kafka", 0.85),
      req("redis-caching", 0.85),
      req("database-sharding", 0.8),
      req("event-driven-architecture", 0.85),
      req("cqrs-pattern", 0.8),
      req("docker", 0.85),
      req("kubernetes", 0.8),
      req("technical-mentoring", 0.85),
    ],
  },
  {
    id: "full-stack-developer",
    title: "Full Stack Developer",
    aliases: ["fullstack developer", "full-stack engineer", "fullstack engineer", "full stack dev", "fullstack dev", "full stack software developer", "fullstack web developer"],
    skills: [
      req("react", 0.9),
      req("nodejs", 0.9),
      req("typescript", 0.95),
      req("javascript", 0.95),
      req("html", 0.85),
      req("css", 0.85),
      req("tailwindcss", 0.8),
      req("postgresql", 0.85),
      req("rest-api", 0.9),
      req("prisma", 0.8),
      req("nextjs", 0.85),
      req("docker", 0.75),
      req("git", 0.85),
    ],
  },
  {
    id: "react-developer",
    title: "React Developer",
    aliases: ["reactjs developer", "react.js developer", "react engineer", "react front end developer", "react specialist"],
    skills: [
      req("react", 1.0),
      req("typescript", 0.95),
      req("javascript", 0.95),
      req("nextjs", 0.85),
      req("redux", 0.8),
      req("zustand", 0.8),
      req("tanstack-query", 0.85),
      req("tailwindcss", 0.85),
      req("shadcn-ui", 0.8),
      req("html", 0.9),
      req("css", 0.9),
      req("jest-unit", 0.75),
    ],
  },
  {
    id: "nodejs-developer",
    title: "Node.js Developer",
    aliases: ["node developer", "node.js engineer", "nodejs engineer", "node backend developer"],
    skills: [
      req("nodejs", 1.0),
      req("typescript", 0.95),
      req("javascript", 0.95),
      req("express", 0.9),
      req("nestjs", 0.85),
      req("postgresql", 0.85),
      req("mongodb", 0.8),
      req("prisma", 0.85),
      req("redis-caching", 0.8),
      req("rest-api", 0.9),
      req("docker", 0.75),
    ],
  },
  {
    id: "python-developer",
    title: "Python Developer",
    aliases: ["python engineer", "python programmer", "python backend engineer", "python software engineer"],
    skills: [
      req("python", 1.0),
      req("fastapi", 0.9),
      req("django", 0.85),
      req("flask", 0.8),
      req("postgresql", 0.85),
      req("sqlalchemy", 0.85),
      req("celery", 0.8),
      req("redis-caching", 0.75),
      req("rest-api", 0.9),
      req("docker", 0.75),
      req("pytest", 0.85),
    ],
  },
  {
    id: "java-developer",
    title: "Java Developer",
    aliases: ["java engineer", "java software engineer", "java backend developer", "j2ee developer", "core java developer"],
    skills: [
      req("java", 1.0),
      req("spring-boot", 0.95),
      req("spring-framework", 0.9),
      req("spring-data", 0.85),
      req("hibernate", 0.85),
      req("postgresql", 0.8),
      req("mysql", 0.8),
      req("apache-kafka", 0.75),
      req("microservices-architecture", 0.85),
      req("junit5", 0.85),
      req("docker", 0.75),
      req("maven", 0.8),
    ],
  },
  {
    id: "go-developer",
    title: "Go Developer",
    aliases: ["golang developer", "golang engineer", "go engineer", "go backend engineer", "golang programmer"],
    skills: [
      req("go", 1.0),
      req("gin", 0.85),
      req("grpc", 0.85),
      req("microservices-architecture", 0.9),
      req("docker", 0.85),
      req("kubernetes", 0.8),
      req("postgresql", 0.8),
      req("redis-caching", 0.8),
      req("rest-api", 0.9),
      req("concurrent-programming", 0.85),
    ],
  },
  {
    id: "rust-developer",
    title: "Rust Developer",
    aliases: ["rust engineer", "rust backend developer", "rust systems engineer", "rustacean"],
    skills: [
      req("rust", 1.0),
      req("tokio", 0.9),
      req("axum", 0.85),
      req("actix", 0.8),
      req("systems-programming", 0.85),
      req("memory-safety", 0.95),
      req("docker", 0.75),
      req("postgresql", 0.75),
      req("grpc", 0.8),
    ],
  },
  {
    id: "dotnet-developer",
    title: ".NET Developer",
    aliases: ["c# developer", "csharp developer", "dot net developer", ".net core developer", "c# .net engineer", "asp.net developer"],
    skills: [
      req("csharp", 1.0),
      req("aspnet-core", 0.95),
      req("entity-framework", 0.9),
      req("sql-server", 0.85),
      req("rest-api", 0.9),
      req("azure", 0.75),
      req("microservices-architecture", 0.8),
      req("xunit-dotnet", 0.8),
      req("docker", 0.7),
    ],
  },
  {
    id: "php-developer",
    title: "PHP Developer",
    aliases: ["php engineer", "laravel developer", "symfony developer", "php backend developer"],
    skills: [
      req("php", 1.0),
      req("laravel", 0.95),
      req("symfony", 0.85),
      req("mysql", 0.85),
      req("postgresql", 0.75),
      req("rest-api", 0.85),
      req("docker", 0.7),
      req("git", 0.8),
    ],
  },
  {
    id: "ruby-developer",
    title: "Ruby Developer",
    aliases: ["ruby on rails developer", "rails developer", "ror developer", "ruby engineer"],
    skills: [
      req("ruby", 1.0),
      req("rails", 0.95),
      req("postgresql", 0.85),
      req("redis-caching", 0.8),
      req("sidekiq", 0.85),
      req("rest-api", 0.85),
      req("docker", 0.7),
    ],
  },
  {
    id: "elixir-developer",
    title: "Elixir Developer",
    aliases: ["elixir engineer", "phoenix developer", "elixir phoenix developer"],
    skills: [
      req("elixir", 1.0),
      req("phoenix", 0.95),
      req("phoenix-liveview", 0.85),
      req("gen-server", 0.9),
      req("postgresql", 0.8),
      req("erlang", 0.75),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 2. Cloud, DevOps, SRE & Platform Engineering
  // ───────────────────────────────────────────────────────────────────
  {
    id: "devops-engineer",
    title: "DevOps Engineer",
    aliases: ["devops", "dev ops engineer", "cloud devops engineer", "infrastructure automation engineer", "build and release engineer", "ci/cd engineer"],
    skills: [
      req("docker", 0.95),
      req("kubernetes", 0.95),
      req("terraform", 0.9),
      req("aws", 0.85),
      req("github-actions", 0.85),
      req("gitlab-ci", 0.8),
      req("linux-administration", 0.9),
      req("bash", 0.85),
      req("ansible", 0.8),
      req("helm", 0.85),
      req("prometheus", 0.8),
      req("grafana", 0.8),
      req("devops-culture", 0.95),
    ],
  },
  {
    id: "senior-devops-engineer",
    title: "Senior DevOps Engineer",
    aliases: ["sr devops engineer", "lead devops engineer", "principal devops engineer", "staff devops engineer"],
    skills: [
      req("kubernetes", 1.0),
      req("terraform", 0.95),
      req("aws", 0.9),
      req("argocd", 0.85),
      req("helm", 0.9),
      req("istio", 0.8),
      req("opentelemetry", 0.85),
      req("datadog", 0.85),
      req("devsecops-discipline", 0.85),
      req("finops", 0.8),
      req("technical-leadership", 0.85),
    ],
  },
  {
    id: "sre-engineer",
    title: "Site Reliability Engineer (SRE)",
    aliases: ["sre", "site reliability engineer", "production reliability engineer", "systems reliability engineer", "infrastructure sre"],
    skills: [
      req("sre-discipline", 1.0),
      req("kubernetes", 0.95),
      req("prometheus", 0.9),
      req("grafana", 0.9),
      req("opentelemetry", 0.85),
      req("datadog", 0.85),
      req("linux-administration", 0.9),
      req("python", 0.8),
      req("go", 0.8),
      req("terraform", 0.85),
      req("incident-response-discipline", 0.85),
      req("chaos-engineering", 0.8),
    ],
  },
  {
    id: "platform-engineer",
    title: "Platform Engineer",
    aliases: ["platform eng", "internal developer platform engineer", "idp engineer", "cloud platform engineer", "developer experience engineer"],
    skills: [
      req("kubernetes", 0.95),
      req("terraform", 0.9),
      req("crossplane", 0.8),
      req("argocd", 0.85),
      req("helm", 0.9),
      req("go", 0.8),
      req("aws", 0.85),
      req("docker", 0.9),
      req("backstage-spotify", 0.75),
      req("gitops-methodology", 0.85),
    ],
  },
  {
    id: "cloud-engineer",
    title: "Cloud Infrastructure Engineer",
    aliases: ["cloud engineer", "cloud infrastructure developer", "cloud systems engineer", "multi cloud engineer"],
    skills: [
      req("aws", 0.9),
      req("azure", 0.8),
      req("gcp", 0.75),
      req("terraform", 0.9),
      req("docker", 0.85),
      req("kubernetes", 0.8),
      req("linux-administration", 0.85),
      req("cloud-computing", 0.95),
      req("finops", 0.75),
    ],
  },
  {
    id: "cloud-architect",
    title: "Cloud Solutions Architect",
    aliases: ["cloud architect", "enterprise cloud architect", "aws solutions architect", "azure cloud architect", "gcp cloud architect"],
    skills: [
      req("cloud-computing", 1.0),
      req("aws", 0.95),
      req("azure", 0.85),
      req("system-design", 0.95),
      req("terraform", 0.9),
      req("kubernetes", 0.85),
      req("microservices-architecture", 0.9),
      req("cloud-security", 0.9),
      req("finops", 0.85),
      req("cloud-migration", 0.9),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 3. Data Engineering, Analytics & Business Intelligence
  // ───────────────────────────────────────────────────────────────────
  {
    id: "data-engineer",
    title: "Data Engineer",
    aliases: ["data pipeline engineer", "big data engineer", "data infrastructure engineer", "etl developer", "data platform engineer"],
    skills: [
      req("python", 0.95),
      req("sql", 1.0),
      req("apache-spark", 0.95),
      req("pyspark", 0.9),
      req("apache-kafka", 0.85),
      req("apache-airflow", 0.85),
      req("dbt", 0.85),
      req("snowflake", 0.85),
      req("bigquery", 0.8),
      req("databricks-lakehouse", 0.85),
      req("delta-lake", 0.8),
      req("parquet", 0.8),
      req("etl-pipeline", 0.95),
      req("data-warehouse-concept", 0.9),
      req("docker", 0.75),
    ],
  },
  {
    id: "senior-data-engineer",
    title: "Senior Data Engineer",
    aliases: ["sr data engineer", "lead data engineer", "staff data engineer", "principal data engineer"],
    skills: [
      req("apache-spark", 1.0),
      req("apache-flink", 0.85),
      req("databricks-lakehouse", 0.95),
      req("snowflake", 0.9),
      req("data-mesh", 0.8),
      req("data-lakehouse-concept", 0.9),
      req("dbt", 0.9),
      req("apache-airflow", 0.9),
      req("apache-kafka", 0.9),
      req("sql", 1.0),
      req("python", 0.95),
      req("great-expectations", 0.8),
      req("technical-mentoring", 0.85),
    ],
  },
  {
    id: "data-analyst",
    title: "Data Analyst",
    aliases: ["business data analyst", "product data analyst", "analytics analyst", "reporting analyst", "quantitative analyst"],
    skills: [
      req("sql", 1.0),
      req("tableau", 0.9),
      req("power-bi", 0.9),
      req("python", 0.8),
      req("pandas", 0.85),
      req("data-visualization", 0.95),
      req("statistical-analysis", 0.85),
      req("data-warehouse-concept", 0.8),
    ],
  },
  {
    id: "analytics-engineer",
    title: "Analytics Engineer",
    aliases: ["analytics eng", "dbt analytics engineer", "data warehouse engineer", "modern data stack engineer"],
    skills: [
      req("sql", 1.0),
      req("dbt", 1.0),
      req("snowflake", 0.9),
      req("bigquery", 0.85),
      req("python", 0.8),
      req("data-modeling-concept", 0.95),
      req("looker", 0.85),
      req("fivetran", 0.8),
      req("git", 0.85),
    ],
  },
  {
    id: "bi-developer",
    title: "Business Intelligence (BI) Developer",
    aliases: ["bi developer", "bi engineer", "power bi developer", "tableau developer", "bi consultant", "business intelligence analyst"],
    skills: [
      req("power-bi", 0.95),
      req("tableau", 0.95),
      req("sql", 1.0),
      req("dax", 0.85),
      req("data-warehouse-concept", 0.9),
      req("data-modeling-concept", 0.85),
      req("ssis-etl", 0.7),
      req("looker", 0.75),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 4. AI, Machine Learning, Data Science & GenAI
  // ───────────────────────────────────────────────────────────────────
  {
    id: "ai-engineer",
    title: "AI Engineer (GenAI / LLM Application Developer)",
    aliases: ["artificial intelligence engineer", "ai developer", "genai engineer", "llm engineer", "generative ai developer", "ai application engineer", "applied ai engineer"],
    skills: [
      req("python", 1.0),
      req("generative-ai", 1.0),
      req("llm", 1.0),
      req("langchain", 0.95),
      req("langgraph", 0.95),
      req("rag", 0.95),
      req("openai-api", 0.95),
      req("anthropic-api", 0.9),
      req("pinecone", 0.85),
      req("pgvector", 0.85),
      req("embeddings", 0.9),
      req("prompt-engineering", 0.9),
      req("ai-agents", 0.9),
      req("langfuse", 0.85),
      req("fastapi", 0.85),
      req("docker", 0.8),
    ],
  },
  {
    id: "ml-engineer",
    title: "Machine Learning Engineer (MLE)",
    aliases: ["machine learning engineer", "mle", "machine learning developer", "applied ml engineer", "ml software engineer"],
    skills: [
      req("python", 1.0),
      req("machine-learning", 1.0),
      req("pytorch", 0.95),
      req("tensorflow", 0.85),
      req("scikit-learn", 0.9),
      req("deep-learning", 0.9),
      req("feature-engineering", 0.9),
      req("mlops-discipline", 0.85),
      req("mlflow", 0.85),
      req("docker", 0.85),
      req("kubernetes", 0.75),
      req("fastapi", 0.8),
      req("xgboost", 0.85),
    ],
  },
  {
    id: "mlops-engineer",
    title: "MLOps Engineer",
    aliases: ["ml ops engineer", "machine learning operations engineer", "ai infrastructure engineer", "ml platform engineer"],
    skills: [
      req("mlops-discipline", 1.0),
      req("mlflow", 0.9),
      req("kubeflow", 0.85),
      req("kubernetes", 0.9),
      req("docker", 0.9),
      req("triton-server", 0.85),
      req("vllm", 0.85),
      req("python", 0.9),
      req("terraform", 0.8),
      req("aws-sagemaker", 0.8),
      req("dvc", 0.8),
      req("wandb", 0.8),
    ],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    aliases: ["ds", "applied scientist", "data science researcher", "quantitative data scientist", "machine learning scientist"],
    skills: [
      req("python", 1.0),
      req("sql", 0.9),
      req("machine-learning", 0.95),
      req("scikit-learn", 0.9),
      req("statistical-analysis", 0.95),
      req("pandas", 0.95),
      req("numpy", 0.9),
      req("data-visualization", 0.85),
      req("deep-learning", 0.8),
      req("pytorch", 0.8),
      req("r", 0.65),
      req("ab-testing-experimentation", 0.85),
    ],
  },
  {
    id: "nlp-engineer",
    title: "NLP Engineer (Natural Language Processing)",
    aliases: ["nlp developer", "natural language processing engineer", "computational linguist", "nlp scientist"],
    skills: [
      req("nlp", 1.0),
      req("python", 1.0),
      req("transformers-architecture", 0.95),
      req("huggingface", 0.95),
      req("pytorch", 0.9),
      req("llm", 0.95),
      req("spacy", 0.85),
      req("named-entity-recognition", 0.85),
      req("fine-tuning", 0.9),
    ],
  },
  {
    id: "cv-engineer",
    title: "Computer Vision Engineer",
    aliases: ["computer vision developer", "cv developer", "vision engineer", "image processing engineer"],
    skills: [
      req("computer-vision", 1.0),
      req("python", 1.0),
      req("opencv", 0.95),
      req("pytorch", 0.95),
      req("cnn", 0.9),
      req("object-detection", 0.9),
      req("image-segmentation", 0.9),
      req("deep-learning", 0.95),
      req("cpp", 0.75),
    ],
  },
  {
    id: "prompt-engineer",
    title: "Prompt Engineer / AI Interaction Designer",
    aliases: ["prompt engineer", "prompt designer", "llm prompt optimizer", "ai interaction designer"],
    skills: [
      req("prompt-engineering", 1.0),
      req("llm", 0.95),
      req("generative-ai", 0.95),
      req("openai-api", 0.9),
      req("anthropic-api", 0.9),
      req("rag", 0.85),
      req("python", 0.75),
      req("langchain", 0.8),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 5. Cybersecurity, InfoSec & GRC
  // ───────────────────────────────────────────────────────────────────
  {
    id: "security-engineer",
    title: "Cybersecurity Engineer",
    aliases: ["security engineer", "infosec engineer", "information security engineer", "cyber security specialist", "cybersecurity developer"],
    skills: [
      req("application-security", 0.9),
      req("cloud-security", 0.9),
      req("network-security", 0.85),
      req("owasp-top-10", 0.9),
      req("penetration-testing", 0.8),
      req("cryptography", 0.8),
      req("hashicorp-vault", 0.8),
      req("python", 0.75),
      req("linux-administration", 0.8),
      req("zero-trust-architecture", 0.85),
    ],
  },
  {
    id: "appsec-engineer",
    title: "Application Security (AppSec) Engineer",
    aliases: ["appsec engineer", "application security specialist", "product security engineer", "prodsec"],
    skills: [
      req("application-security", 1.0),
      req("owasp-top-10", 1.0),
      req("sast-dast", 0.95),
      req("snyk-security", 0.9),
      req("threat-modeling", 0.9),
      req("penetration-testing", 0.85),
      req("devsecops-discipline", 0.9),
      req("software-supply-chain-security", 0.85),
    ],
  },
  {
    id: "cloud-security-engineer",
    title: "Cloud Security Engineer",
    aliases: ["cloud sec engineer", "aws security specialist", "azure security engineer", "cloud secops"],
    skills: [
      req("cloud-security", 1.0),
      req("cspm", 0.95),
      req("wiz-security", 0.9),
      req("aws-iam", 0.95),
      req("terraform", 0.85),
      req("kubernetes-security", 0.85),
      req("zero-trust-architecture", 0.9),
      req("azure-defender", 0.8),
    ],
  },
  {
    id: "penetration-tester",
    title: "Penetration Tester (Ethical Hacker / Red Teamer)",
    aliases: ["pentest engineer", "ethical hacker", "security tester", "red teamer", "offensive security engineer"],
    skills: [
      req("penetration-testing", 1.0),
      req("burp-suite", 0.95),
      req("metasploit", 0.9),
      req("nmap", 0.9),
      req("wireshark", 0.85),
      req("owasp-top-10", 0.95),
      req("vulnerability-management", 0.9),
      req("python", 0.8),
      req("bash", 0.8),
    ],
  },
  {
    id: "soc-analyst",
    title: "Security Operations Center (SOC) Analyst",
    aliases: ["soc analyst", "soc tier 1", "soc tier 2", "security analyst", "cyber threat analyst"],
    skills: [
      req("soc-operations", 1.0),
      req("siem-platform", 0.95),
      req("splunk", 0.9),
      req("crowdstrike-falcon", 0.85),
      req("incident-response-discipline", 0.9),
      req("threat-intelligence", 0.85),
      req("edr-xdr", 0.9),
    ],
  },
  {
    id: "grc-analyst",
    title: "GRC & Compliance Analyst",
    aliases: ["grc analyst", "compliance analyst", "it compliance manager", "security compliance auditor", "information security risk analyst"],
    skills: [
      req("grc-framework", 1.0),
      req("soc2-compliance", 0.95),
      req("iso-27001", 0.95),
      req("gdpr-compliance", 0.9),
      req("hipaa-compliance", 0.85),
      req("nist-cybersecurity-framework", 0.9),
      req("pci-dss-compliance", 0.85),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 6. Mobile & Spatial Computing
  // ───────────────────────────────────────────────────────────────────
  {
    id: "ios-developer",
    title: "iOS Developer",
    aliases: ["ios engineer", "swift developer", "iphone developer", "apple ios developer", "senior ios engineer"],
    skills: [
      req("swift", 1.0),
      req("swiftui", 0.95),
      req("uikit", 0.9),
      req("xcode", 0.95),
      req("ios-development", 1.0),
      req("swiftdata", 0.8),
      req("core-data", 0.85),
      req("combine-framework", 0.8),
      req("fastlane", 0.8),
      req("rest-api", 0.85),
    ],
  },
  {
    id: "android-developer",
    title: "Android Developer",
    aliases: ["android engineer", "kotlin android developer", "android mobile developer", "senior android engineer"],
    skills: [
      req("kotlin", 1.0),
      req("jetpack-compose", 0.95),
      req("android-sdk", 0.95),
      req("android-studio", 0.95),
      req("android-development", 1.0),
      req("kotlin-coroutines", 0.95),
      req("room-database", 0.85),
      req("dagger-hilt", 0.85),
      req("gradle-android", 0.8),
      req("rest-api", 0.85),
    ],
  },
  {
    id: "react-native-developer",
    title: "React Native Developer",
    aliases: ["react native engineer", "rn developer", "cross platform mobile developer", "react native mobile engineer"],
    skills: [
      req("react-native", 1.0),
      req("react", 0.95),
      req("typescript", 0.95),
      req("javascript", 0.95),
      req("expo-framework", 0.9),
      req("fastlane", 0.75),
      req("rest-api", 0.85),
      req("firebase-mobile", 0.8),
      req("detox-testing", 0.75),
    ],
  },
  {
    id: "flutter-developer",
    title: "Flutter Developer",
    aliases: ["flutter engineer", "dart developer", "flutter mobile developer", "google flutter developer"],
    skills: [
      req("flutter", 1.0),
      req("dart", 1.0),
      req("flutter-bloc", 0.85),
      req("riverpod", 0.85),
      req("firebase-mobile", 0.85),
      req("rest-api", 0.85),
      req("fastlane", 0.7),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 7. QA, SDET & Test Automation
  // ───────────────────────────────────────────────────────────────────
  {
    id: "sdet",
    title: "Software Development Engineer in Test (SDET)",
    aliases: ["sdet", "test automation engineer", "qa automation engineer", "software test engineer in test", "automation test lead"],
    skills: [
      req("playwright", 0.95),
      req("cypress", 0.9),
      req("selenium-webdriver", 0.85),
      req("typescript", 0.9),
      req("python", 0.85),
      req("jest-unit", 0.85),
      req("pytest", 0.85),
      req("test-automation-architecture", 1.0),
      req("ci/cd-testing", 0.85),
      req("k6-load-testing", 0.8),
      req("postman-api-testing", 0.85),
    ],
  },
  {
    id: "qa-engineer",
    title: "QA Engineer (Manual & Automated)",
    aliases: ["qa engineer", "quality assurance analyst", "software tester", "qa tester", "manual qa engineer"],
    skills: [
      req("qa-strategy", 1.0),
      req("postman-api-testing", 0.85),
      req("jira-software", 0.85),
      req("selenium-webdriver", 0.75),
      req("playwright", 0.75),
      req("sql", 0.75),
      req("agile-methodology", 0.8),
    ],
  },
  {
    id: "performance-engineer",
    title: "Performance & Load Test Engineer",
    aliases: ["performance engineer", "load test engineer", "performance testing specialist"],
    skills: [
      req("k6-load-testing", 0.95),
      req("apache-jmeter", 0.95),
      req("gatling", 0.85),
      req("grafana", 0.85),
      req("prometheus", 0.8),
      req("datadog", 0.8),
      req("query-optimization", 0.8),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 8. Product, Design & Architecture Leadership
  // ───────────────────────────────────────────────────────────────────
  {
    id: "product-designer",
    title: "Product Designer (UI/UX)",
    aliases: ["product designer", "ui/ux designer", "senior product designer", "lead product designer", "ux/ui designer", "digital product designer"],
    skills: [
      req("figma", 1.0),
      req("ux-design", 1.0),
      req("ui-design", 1.0),
      req("product-design-discipline", 1.0),
      req("user-research", 0.9),
      req("design-systems-discipline", 0.95),
      req("interactive-prototyping", 0.9),
      req("wireframing", 0.9),
      req("responsive-ui-design", 0.85),
      req("accessible-design", 0.85),
    ],
  },
  {
    id: "ux-researcher",
    title: "UX Researcher (User Researcher)",
    aliases: ["ux researcher", "user experience researcher", "user researcher", "design researcher"],
    skills: [
      req("user-research", 1.0),
      req("ux-design", 0.85),
      req("information-architecture", 0.85),
      req("miro-whiteboard", 0.85),
      req("figma", 0.75),
    ],
  },
  {
    id: "product-manager",
    title: "Product Manager (PM)",
    aliases: ["product manager", "pm", "technical product manager", "tpm", "group product manager", "senior product manager"],
    skills: [
      req("product-management", 1.0),
      req("product-roadmapping", 1.0),
      req("user-story-mapping", 0.95),
      req("agile-methodology", 0.9),
      req("scrum-framework", 0.9),
      req("jira-software", 0.9),
      req("amplitude-analytics", 0.85),
      req("ab-testing-experimentation", 0.85),
      req("north-star-metrics", 0.9),
      req("cross-functional-collaboration", 0.95),
    ],
  },
  {
    id: "technical-product-manager",
    title: "Technical Product Manager (TPM)",
    aliases: ["technical pm", "tpm", "technical product lead"],
    skills: [
      req("product-management", 0.95),
      req("system-design", 0.85),
      req("rest-api", 0.85),
      req("sql", 0.85),
      req("agile-methodology", 0.9),
      req("product-roadmapping", 0.9),
      req("cloud-computing", 0.75),
    ],
  },
  {
    id: "engineering-manager",
    title: "Engineering Manager (EM)",
    aliases: ["engineering manager", "em", "software engineering manager", "development manager", "head of engineering"],
    skills: [
      req("engineering-management", 1.0),
      req("technical-leadership", 0.95),
      req("agile-methodology", 0.9),
      req("scrum-framework", 0.85),
      req("technical-mentoring", 0.95),
      req("cross-functional-collaboration", 0.95),
      req("system-design", 0.8),
    ],
  },
  {
    id: "tech-lead",
    title: "Tech Lead / Lead Developer",
    aliases: ["tech lead", "technical lead", "lead engineer", "lead developer", "software team lead"],
    skills: [
      req("technical-leadership", 1.0),
      req("system-design", 0.95),
      req("code-review", 0.95),
      req("technical-mentoring", 0.9),
      req("clean-architecture", 0.9),
      req("microservices-architecture", 0.85),
      req("agile-methodology", 0.8),
    ],
  },
  {
    id: "staff-engineer",
    title: "Staff Software Engineer",
    aliases: ["staff engineer", "staff swe", "staff developer"],
    skills: [
      req("system-design", 1.0),
      req("distributed-systems", 0.95),
      req("technical-leadership", 0.95),
      req("clean-architecture", 0.95),
      req("microservices-architecture", 0.9),
      req("scalability", 0.95),
      req("technical-writing-discipline", 0.9),
    ],
  },
  {
    id: "principal-engineer",
    title: "Principal Software Engineer",
    aliases: ["principal engineer", "principal swe", "distinguished engineer", "fellow"],
    skills: [
      req("system-design", 1.0),
      req("distributed-systems", 1.0),
      req("technical-leadership", 1.0),
      req("cloud-computing", 0.9),
      req("domain-driven-design", 0.95),
      req("scalability", 1.0),
    ],
  },
  {
    id: "software-architect",
    title: "Solutions & Software Architect",
    aliases: ["software architect", "solutions architect", "application architect", "enterprise architect"],
    skills: [
      req("system-design", 1.0),
      req("microservices-architecture", 1.0),
      req("domain-driven-design", 0.95),
      req("event-driven-architecture", 0.95),
      req("distributed-systems", 0.95),
      req("cloud-computing", 0.95),
      req("clean-architecture", 0.95),
    ],
  },
  {
    id: "cto-vp-engineering",
    title: "CTO / VP of Engineering",
    aliases: ["cto", "chief technology officer", "vp of engineering", "vp engineering", "vice president engineering"],
    skills: [
      req("technical-leadership", 1.0),
      req("engineering-management", 1.0),
      req("system-design", 0.9),
      req("cloud-computing", 0.85),
      req("cross-functional-collaboration", 1.0),
      req("product-roadmapping", 0.85),
    ],
  },

  // ───────────────────────────────────────────────────────────────────
  // 9. Systems, Embedded, Game Dev, Blockchain & Enterprise
  // ───────────────────────────────────────────────────────────────────
  {
    id: "embedded-systems-engineer",
    title: "Embedded Systems & Firmware Engineer",
    aliases: ["embedded engineer", "firmware engineer", "embedded software engineer", "mcu engineer"],
    skills: [
      req("c", 1.0),
      req("cpp", 0.9),
      req("embedded-systems-engineering", 1.0),
      req("microcontrollers", 0.95),
      req("arm-cortex", 0.9),
      req("freertos", 0.9),
      req("stm32", 0.85),
      req("linux-kernel", 0.75),
    ],
  },
  {
    id: "robotics-engineer",
    title: "Robotics Software Engineer",
    aliases: ["robotics engineer", "ros developer", "autonomous systems engineer"],
    skills: [
      req("ros-robotics", 1.0),
      req("cpp", 0.95),
      req("python", 0.9),
      req("slam-robotics", 0.9),
      req("gazebo-simulation", 0.85),
      req("computer-vision", 0.85),
      req("embedded-systems-engineering", 0.8),
    ],
  },
  {
    id: "unity-game-developer",
    title: "Unity Game Developer",
    aliases: ["unity developer", "unity programmer", "unity3d developer", "unity gameplay programmer"],
    skills: [
      req("unity-engine", 1.0),
      req("csharp", 1.0),
      req("computer-graphics-api", 0.8),
      req("physics-engines", 0.8),
      req("data-structures", 0.85),
    ],
  },
  {
    id: "unreal-engine-developer",
    title: "Unreal Engine (C++) Developer",
    aliases: ["unreal developer", "ue5 developer", "unreal engine programmer", "gameplay programmer unreal"],
    skills: [
      req("unreal-engine", 1.0),
      req("cpp", 1.0),
      req("computer-graphics-api", 0.85),
      req("physics-engines", 0.85),
      req("data-structures", 0.85),
    ],
  },
  {
    id: "blockchain-smart-contract-developer",
    title: "Blockchain & Smart Contract Developer (Web3)",
    aliases: ["smart contract developer", "solidity developer", "web3 developer", "blockchain engineer", "ethereum developer"],
    skills: [
      req("solidity", 1.0),
      req("smart-contracts", 1.0),
      req("foundry-toolkit", 0.9),
      req("hardhat", 0.9),
      req("ethereum", 0.95),
      req("openzeppelin", 0.9),
      req("ethers-js", 0.85),
      req("viem-library", 0.85),
      req("smart-contract-auditing", 0.85),
    ],
  },
  {
    id: "solana-developer",
    title: "Solana Developer",
    aliases: ["solana engineer", "anchor developer", "solana web3 developer"],
    skills: [
      req("rust", 1.0),
      req("solana-blockchain", 1.0),
      req("anchor-framework", 0.95),
      req("typescript", 0.85),
    ],
  },
  {
    id: "salesforce-developer",
    title: "Salesforce Developer",
    aliases: ["salesforce developer", "sfdc developer", "salesforce engineer", "salesforce technical consultant"],
    skills: [
      req("salesforce", 1.0),
      req("salesforce-apex", 1.0),
      req("salesforce-lightning", 0.95),
      req("javascript", 0.8),
      req("sql", 0.75),
    ],
  },
  {
    id: "sap-consultant",
    title: "SAP ABAP / S/4HANA Consultant",
    aliases: ["sap consultant", "sap abap developer", "sap functional consultant", "sap technical consultant"],
    skills: [
      req("sap-erp", 1.0),
      req("sap-abap", 1.0),
      req("sap-hana-db", 0.9),
      req("sql", 0.8),
    ],
  },
  {
    id: "servicenow-developer",
    title: "ServiceNow Developer",
    aliases: ["servicenow developer", "servicenow administrator", "servicenow consultant", "servicenow itsm developer"],
    skills: [
      req("servicenow-platform", 1.0),
      req("javascript", 0.9),
      req("rest-api", 0.8),
    ],
  },
  {
    id: "shopify-developer",
    title: "Shopify Theme & App Developer",
    aliases: ["shopify developer", "shopify plus developer", "shopify expert", "ecommerce developer shopify"],
    skills: [
      req("shopify-platform", 1.0),
      req("javascript", 0.9),
      req("html", 0.9),
      req("css", 0.9),
      req("react", 0.8),
      req("graphql-api", 0.8),
    ],
  },
];
